name: lua
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_media_metadata: ^1.0.0+1
  get_it: ^7.7.0
  just_audio: ^0.9.38
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
